### PR TITLE
Tests for JSON and Text with returnRawBody

### PR DESCRIPTION
**Pull request by zevisert**
Thought I'd help out with [dlau/koa-body #113](https://github.com/dlau/koa-body/pull/113) since I need raw body access in the project I'm working on and they're waiting for tests

You should be able to merge this here, then it'll update the base PR and @MarkHerhold can merge your original PR

### CODE REVIEW

**Comment by MarkHerhold** [comment]
This looks good. If the original author, @thuitaw does not merge this in, I can manually add the tests.

**Comment by MarkHerhold** [comment]
Ok, no response so far. @zevisert  do you want me to just manually add the changes?

**Comment by zevisert** [comment]
Feel free. I'm not doing anything right now, would it help if I send it as a PR on your master?

**Comment by MarkHerhold** [comment]
That would be so much better. Thanks @zevisert

**Pull request closed without merging**
